### ISSUE TITLE
 Change profile settings

### ISSUE THREAD

**Issue by pyronlaboratory** [joealcorn/xbox#11]
Hi Joe,

Great work on this api!
I wanted to know if we can change profile settings as well..
For instance, lets say I want to change my gamertag to something that is available. 
How do we go about it?

Thanks!

**Comment by pyronlaboratory** [comment]
Additional information: I wish to redeem my one free claim, so no monetary api's are required here!

**Comment by joealcorn** [comment]
Hi Ronit,

I've replied to your query by email, but the tldr for anybody else who comes across this issue is that it simply has never been implemented. I haven't touched this code in 5 years and have no intention of picking it back up, so if this ever happens it'll likely be because somebody wanted it to happen badly enough.

**Comment by pyronlaboratory** [comment]
I've accomplished the requirement, so anyone looking for it (in the future) can send me an email.
Cheers!
